### ISSUE TITLE
Epic 1

### ISSUE THREAD

**Issue by Jochim** [Synergistic-Management-Solutions/test-play#1]
```[tasklist]
### Stage 1
- [ ] https://github.com/Synergistic-Management-Solutions/test-play/issues/2
- [ ] https://github.com/Synergistic-Management-Solutions/test-play/issues/3
- [ ] https://github.com/Synergistic-Management-Solutions/test-play/issues/7
```
```[tasklist]
### Stage 2
- [ ] https://github.com/Synergistic-Management-Solutions/test-play/issues/4
- [ ] https://github.com/Synergistic-Management-Solutions/test-play/issues/8
- [ ] https://github.com/Synergistic-Management-Solutions/MotiMe/issues/1
```

```[tasklist]
### Tasks
```
